- hosts: bench
  user: root
  become: yes
  gather_facts: yes
  vars:
    golang_version: 1.13

  roles:
    - user.isucon
    - bootstrap
    - external.deploy

    - kernel-tune
    - nginx
    - nginx.log-format
    - golang
    - external.benchmarker

  tasks:
    - name: Start default daemons
      become: yes
      become_user: root
      systemd:
        name: "{{ item }}"
        state: restarted
        daemon_reload: yes
        enabled: yes
      with_items:
        - nginx.service
